config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'host' , to: 'pages#host'
  get 'terms' , to: 'pages#terms'
  get '/terms/privacy_policy' , to: 'pages#privacy'
  get '/terms/nondiscrimination_policy' , to: 'pages#nondiscrimination'
  get '/terms/payments_terms' , to: 'pages#payments'
  get '/terms/host_guarantee' , to: 'pages#host_guarantee'
  get '/terms/guest_refund_policy' , to: 'pages#guest_refund'
  get '/terms/copyright_policy' , to: 'pages#copyright'
  get '/terms/cookie_policy' , to: 'pages#cookie'
  get '/terms/guest_waiver' , to: 'pages#guest_waiver'
  get '/how_it_works' , to: 'pages#how_it_works'
  get '/how_it_works/for_gyms' , to: 'pages#for_gyms'
  get '/how_it_works/for_trainers' , to: 'pages#for_trainers'
  get '/how_it_works/for_clients_and_guests' , to: 'pages#for_clients_and_guests'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'edit', sign_up: 'register'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  
  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end
  
  resources :gyms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :calendars
  end
  
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  
  get '/your_bookings' => 'reservations#your_bookings'
  get '/your_reservations' => 'reservations#your_reservations'
  
  get 'search' => 'pages#search'
  get 'dashboard' => 'dashboards#index'
  
  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end
  
  resources :revenues, only: [:index]
  
  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end
  
  get '/host_calendar' => "calendars#host"
  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"
  
  get '/notification_settings' => 'settings#edit'
  post '/notification_settings' => 'settings#update'
end

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class="navbar-nav navbar-left no-bullet">
      <li>&copy; 2018 Circle Fitness Technologies, Inc.</li>
      <li><%= link_to 'Terms', terms_path %></li>
      <li><%= link_to 'Privacy', terms_privacy_policy_path %></li>
    </ul>
    <ul class="navbar-nav navbar-right no-bullet">
      <li><%= link_to 'Become a Host', host_path %></li>
      <li><%= link_to 'How it Works', how_it_works_path %></li>
      <li><%= link_to 'For Gyms', how_it_works_for_gyms_path %></li>
      <li><%= link_to 'For Trainers', how_it_works_for_trainers_path %></li>
      <li><%= link_to 'For Clients and Guests', how_it_works_for_clients_and_guests_path %></li>
    </ul>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if (!user_signed_in?) %>
        <%= link_to "circle", root_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to "circle", root_path, class: "navbar-brand user" %>
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: '  Try "Santa Monica"', class: "form-control" %>
        </div>
      <% end %>

      
      <% if (!user_signed_in?) %>
      <ul class="nav navbar-nav navbar-right guest">
        <li><%= link_to 'Become a Host', host_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>        
      </ul>
      <% end %>
      
      
      <% if (user_signed_in?) %>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.gyms.count < 0 %>
          <li>
            <button class="btn btn-default btn-host btn-small">
              <%= link_to "Become a host", new_gym_path, style: "text-decoration: none;" %>
            </button>
          </li>
        <% end %>         
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                  role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", dashboard_path %>
              </li>
              <hr>
              <li><%= link_to "Edit Profile", edit_user_registration_path %>
              </li>
              <hr>
              <li><%= link_to "Manage Listings", gyms_path %></li>
              <hr>
              <li><%= link_to "List Your Space", new_gym_path %></li>
              <hr>
              <li><%= link_to "Your Reservations", your_reservations_path %></li>
              <hr>
              <li><%= link_to "Your Bookings", your_bookings_path %></li>
              <hr>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>


<% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/gyms/#{params[:id]}")%>
   
    <nav class="navbar navbar-default dashboard">
      <div class="container">
        <ul class="nav navbar-nav">
          <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "Dashboard", dashboard_path %></li>
          <li <% if current_page?(payment_method_path) %> class="active" <% end %> ><%= link_to "Account Settings", payment_method_path %></li>
          <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "Messages", conversations_path %></li>
          
          <% if !@gyms.blank? %>
            <li <% if current_page?(gyms_path) %> class="active" <% end %> ><%= link_to "Manage Listings", gyms_path %></li>
            <li <% if current_page?(host_calendar_path) %> class="active" <% end %> ><%= link_to "Host Calendar", host_calendar_path %></li>
            <li <% if current_page?(revenues_path) %> class="active" <% end %> ><%= link_to "Revenues", revenues_path %></li>
          <% end %>
          
        </ul>
      </div>
    </nav>
    
<% end %>