config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'host' , to: 'pages#host'
  get 'terms' , to: 'pages#terms'
  get '/terms/privacy_policy' , to: 'pages#privacy'
  get '/terms/nondiscrimination_policy' , to: 'pages#nondiscrimination'
  get '/terms/payments_terms' , to: 'pages#payments'
  get '/terms/host_guarantee' , to: 'pages#host_guarantee'
  get '/terms/guest_refund_policy' , to: 'pages#guest_refund'
  get '/terms/copyright_policy' , to: 'pages#copyright'
  get '/terms/cookie_policy' , to: 'pages#cookie'
  get '/terms/guest_waiver' , to: 'pages#guest_waiver'
  get '/how_it_works' , to: 'pages#how_it_works'
  get '/how_it_works/for_gyms' , to: 'pages#for_gyms'
  get '/how_it_works/for_trainers' , to: 'pages#for_trainers'
  get '/how_it_works/for_clients_and_guests' , to: 'pages#for_clients_and_guests'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'edit', sign_up: 'register'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  
  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end
  
  resources :gyms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
    resources :calendars
  end
  
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]
  
  get '/your_bookings' => 'reservations#your_bookings'
  get '/your_reservations' => 'reservations#your_reservations'
  
  get 'search' => 'pages#search'
  get 'dashboard' => 'dashboards#index'
  
  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => "reservations#approve"
      post '/decline' => "reservations#decline"
    end
  end
  
  resources :revenues, only: [:index]
  
  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end
  
  get '/host_calendar' => "calendars#host"
  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"
  
  get '/notification_settings' => 'settings#edit'
  post '/notification_settings' => 'settings#update'
end

app/models/gym.rb
class Gym < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}
  
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :guest_reviews
  has_many :calendars
  
  geocoded_by :address_string
  after_validation :geocode, if: :address_string_changed?
  
  validates :gym_type, presence: true
  
  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end
  
  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]
  
  def index
    @gyms = current_user.gyms
  end

  def new
    @gym = current_user.gyms.build
  end

  def create
    if !current_user.is_active_host
      return redirect_to payout_method_path, alert: "Please Connect to Stripe Express first."
    end
    
    @gym = current_user.gyms.build(gym_params)
    if @gym.save
      redirect_to listing_gym_path(@gym), notice: "Saved."
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end
  
  def show
    @photos = @gym.photos
    @user = @gym.user
    @guest_reviews = @gym.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @gym.photos
  end

  def amenities
  end

  def location
  end

  def update
    new_params = gym_params
    new_params = gym_params.merge(active: true) if is_ready_gym
    
    if @gym.update(gym_params)
      flash[:notice] = "Saved."
    else
      flash[:alert] = "Something went wrong."
    end
    redirect_back(fallback_location: request.referer)
  end
  
  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @gym)
    }

    render json: output
  end
  
  # --- Reservations ---
  def preload
    today = Date.today
    
    unavailable_dates = @gym.calendars.where("status = ? AND day > ?", 1, today)
    
    special_dates = @gym.calendars.where("status = ? AND day > ? AND price <> ?",0, today, @gym.price)

    render json: {
        unavailable_dates: unavailable_dates,
        special_dates: special_dates
    }
  end
  
  private
    def is_conflict(start_date, end_date, gym)
      check = gym.calendars.where("day BETWEEN ? AND ? AND status = ?", start_date, end_date, 1).limit(1)

      check.size > 0? true : false
    end
  
    def set_gym
      @gym = Gym.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission." unless current_user.id == @gym.user_id
    end

    def is_ready_gym
      !@gym.active && !@gym.price.blank? && !@gym.listing_name.blank? && !@gym.photos.blank? && !@gym.address_string.blank?
    end

    def gym_params
      params.require(:gym).permit(:gym_type, :listing_name, :summary, :address_string, :is_internet, :is_lounge, :is_pool, :is_shower, :is_towel, :is_yoga, :is_cycling, :is_pilates, :is_basketball, :is_childcare, :is_weights, :is_boxing, :price, :active, :instant)
    end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_gym_menu.html.erb
<ul class="sidebar-list">
 
  <% if current_page?(listing_gym_path) %>
  <li class="sidebar-item">
    <%= link_to "Listing", listing_gym_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <% else %>
  <li class="sidebar-item">
    <%= link_to "Listing", listing_gym_path, class: "sidebar-link" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <% end %>
  
  <% if current_page?(pricing_gym_path) %>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_gym_path, class: "sidebar-link active" %>
    <% if !@gym.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <% else %>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_gym_path, class: "sidebar-link" %>
    <% if !@gym.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <% end %>
  
  <% if current_page?(description_gym_path) %>
  <li class="sidebar-item">
    <%= link_to "Description", description_gym_path, class: "sidebar-link active" %>
    <% if !@gym.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <% else %>
  <li class="sidebar-item">
    <%= link_to "Description", description_gym_path, class: "sidebar-link" %>
    <% if !@gym.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <% end %>
  
  <% if current_page?(photo_upload_gym_path) %>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_gym_path, class: "sidebar-link active" %>
    <% if !@gym.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <% else %>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_gym_path, class: "sidebar-link" %>
    <% if !@gym.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <% end %>
  
  <% if current_page?(amenities_gym_path) %>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_gym_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <% else %>
    <li class="sidebar-item">
    <%= link_to "Amenities", amenities_gym_path, class: "sidebar-link" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <% end %>
  
  <% if current_page?(location_gym_path) %>
  <li class="sidebar-item">
    <%= link_to "Location", location_gym_path, class: "sidebar-link active" %>
    <% if !@gym.address_string.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <% else %>
  <li class="sidebar-item">
    <%= link_to "Location", location_gym_path, class: "sidebar-link" %>
    <% if !@gym.address_string.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <% end %>
  
</ul> 
<hr>

<% is_ready = !@gym.active && !@gym.price.blank? && !@gym.listing_name.blank? && !@gym.photos.blank? && !@gym.address_string.blank? %>

<%= form_for @gym do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-save btn-block", disabled: !is_ready %>
<% end %>

app/views/gyms/_gyms_list.html.erb
<% gyms.each do |gym| %>
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= link_to image_tag(gym.cover_photo(:medium)), gym %>
      </div>
      <div class="panel-body">
        <h6><%= gym.gym_type %></h6>
        <h5><%= link_to gym.listing_name, gym %></h5>
        $<%= gym.price %> per day
        <div id="star_<%= gym.id %>"></div>
      </div>
    </div>
  </div>

  <script>
    $('#star_<%= gym.id %>').raty({
      path: '/assets',
      readOnly: true,
      score: <%= gym.average_rating %>
    });
  </script>
<% end %>

app/views/gyms/amenities.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'gym_menu' %>
      <br>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Amenities</div>
        <div class="panel-body">
          <div class="container">
            <%= form_for @gym do |f| %>
              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_weights %> Free weights / Machines
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_lounge %> Lounge
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_shower %> Shower
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_towel %> Towel Service
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_yoga %> Yoga equipment
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_cycling %> Indoor Cycling Bikes
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_pilates %> Pilates equipment
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_pool %> Swimming Pool
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_basketball %> Basketball Court
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_childcare %> Childcare available
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_internet %> Internet
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_boxing %> Boxing equipment
                </div>
              </div>
              <br/><br/>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-save" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>  
    </div>
  </div>  
</div>

app/views/gyms/create.html.erb
<h1>Gyms#create</h1>
<p>Find me in app/views/gyms/create.html.erb</p>

app/views/gyms/description.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'gym_menu' %>
      <br>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Description</div>
        <div class="panel-body">
          <div class="container">
            <%= form_for @gym do |f| %>

            <div class="row">
              <div class="form-group">
              <label>Listing name</label>
                <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
              <label>Summary</label>
                <%= f.text_area :summary, rows: 5, placeholder: "Tell other people about your gym.", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-save" %>
              <% end %>
            </div>
          </div>
        </div>  
      </div>
    </div>
  </div>
</div>

app/views/gyms/index.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <ul class="sidebar-list">
        <li class="sidebar-item"><%= link_to "Your Listings", gyms_path, class: "sidebar-link active" %></li>
        <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
        <li class="sidebar-item"><%= link_to "Your Bookings", your_bookings_path, class: "sidebar-link" %></li>
      </ul>
    </div>
    <% if @gyms.count > 0 %>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          Listings
        </div>
        <div class="panel-body">
          <% @gyms.each do |gym| %>
            <div class="row">
              <div class="col-md-2">
                <%= image_tag gym.cover_photo(:thumb) %>
              </div>
              <div class="col-md-7">
                <h4><%= gym.listing_name %></h4>
              </div>
              <div class="col-md-3 right">
                <%= link_to "Update", listing_gym_path(gym), class: "btn btn-update" %>
              </div>
            </div>
            <hr/>
          <% end %>
        </div>
      </div>
    </div>
    <% else %>
      <div class="col-md-6 text-center">
        <h3>You don't have any listings.</h3>
        <a href="/gyms/new" role="button" class="text-babu">
          <i class="fa fa-plus-circle fa-3x"></i>
        </a>
      </div>
    <% end %>
  </div>  
</div>

app/views/gyms/listing.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'gym_menu' %>
      <br>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Listing</div>
        <div class="panel-body">
          <div class="container">
            <%= form_for @gym do |f| %>

              <div class="row">
                <div class="col-md-4 select">
                  <div class="form-group">
                    <label>Gym Type</label>
                    <br>
                    <%= f.select :gym_type, [["Fitness Center", "Fitness Center"], ["Crossfit Box", "Crossfit Box"], ["Studio", "Studio"], ["Sports Training", "Sports Training"]],
                                  id: "gym_type", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-4 select">
                  <div class="form-group">
                    <label>Booking Type</label>
                    <%= f.select :instant, Gym.instants.map {|key,value| [key.humanize, key]}, selected: @gym.Request? ? 'Request' : 'Instant', prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
              </div>

              <div><%= f.submit "Save", class: "btn btn-save" %></div>

            <% end %>
          </div>
        </div>
      </div>  
    </div>
  </div> 
</div>

app/views/gyms/location.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'gym_menu' %>
      <br>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Location</div>
        <div class="panel-body">
          <br>
          <div class="container">
            <%= form_for @gym do |f| %>

              <div class="row">
                <div class="form-group">
                  <%= f.text_field :address_string, placeholder: "What is your address?", class: "form-control", required: true %>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-submit" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>  
    </div>
  </div> 
</div>

app/views/gyms/new.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <div class="alert alert-warning alert-dismissible d-none d-lg-block" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="alert-link"></span> This is the very beginning of your Listing!
      </div>
      <br>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Create your listing</div>
        <div class="panel-body">
          <div class="container">
            <%= form_for @gym do |f| %>

              <div class="row">
                <div class="col-md-4 select">
                  <div class="form-group">
                    <label>Gym Type</label>
                    <br>
                    <%= f.select :gym_type, [["Fitness Center", "Fitness Center"], ["Crossfit Box", "Crossfit Box"], ["Studio", "Studio"], ["Sports Training", "Sports Training"]],
                                  id: "gym_type", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-4 select">
                  <div class="form-group">
                    <label>Booking Type</label>
                    <%= f.select :instant, Gym.instants.map {|key,value| [key.humanize, key]}, selected: @gym.Request? ? 'Request' : 'Instant', prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
              </div>

              <div><%= f.submit "Create Listing", class: "btn btn-submit" %></div>

              <br>

            <% end %>

          </div> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gyms/photo_upload.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'gym_menu' %>
      <br>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">

        <div class="panel-heading">
          Photos
        </div>

        <div class="panel-body">
          <div class="container">
            <div class="row">
              <div class="col-md-offset-3 col-md-6">
                <br>
                <%= form_for @gym, url: gym_photos_path(@gym), method: 'post', html: {multipart: true} do |f| %>
                  <div class="row">
                    <div class="form-group">
                      <span class="btn btn-default btn-file text-babu">
                        <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                        <%= file_field_tag "images[]", type: :file, multiple: true %>
                      </span>
                    </div>
                  </div>

                  <div class="text-center">
                    <%= f.submit "Add Photos", class: "btn btn-save" %>
                  </div>

                <% end %>
              </div>
            </div>

            <div id="photos"><%= render 'photos/photos_list' %></div>

          </div>
        </div>
      </div>
    </div>
  </div>  
</div>

app/views/gyms/pricing.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'gym_menu' %>
      <br>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Price</div>
        <div class="panel-body">
          <div class="container">
            <%= form_for @gym do |f| %>

              <div class="row">
                <div class="form-group">
                  <%= f.text_field :price, placeholder: "Set your daily price. e.g. 60", class: "form-control", required: true %>
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-save" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>  
    </div>
  </div> 
</div> 

app/views/gyms/show.html.erb
<div class="container content">
  <div class="row">
    <!-- Left Panel -->
    <div class="col-md-8">
      <!-- Listing Name -->  
      <div class="row">
        <div class="col-md-12">

          <br>
          <div class="panel panel-default img">
            <div class="text-center">
              <h3><%= @gym.listing_name %></h3> 
            </div>
            <div class="panel-body text-center">
              <% if @photos.length > 0 %>
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                  <!-- Indicators -->
                  <ol class="carousel-indicators">
                    <% @photos.each do |photo| %>
                        <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
                    <% end %>
                  </ol>

                  <!-- Wrapper for slides -->
                  <div class="carousel-inner">
                    <% @photos.each do |photo| %>
                        <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                          <%= image_tag photo.image.url() %>
                        </div>
                    <% end %>
                  </div> 
                  <!-- Left and right controls -->
                  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                  </a>           
                </div>
              <% end %>
            </div>
          </div>
        </div> 
      </div>
      <hr>
      <!-- Gym Owner Info -->
      <div class="row">
        <div class="text-center">
        <%= image_tag avatar_url(@gym.user), class: "img-circle avatar-large" %><br/><br/>
        <%= link_to @gym.user.first_name, @user %>
      </div> 
      </div>
      <hr>
      <!-- Gym Info -->
      <div class="row text-center">
        <div class="row">
          <div>
            <i class="fa fa-building-o fa-2x text-babu"></i>&nbsp;
            <%= @gym.gym_type %>
            <br><br>
            <%= @gym.address_string %>
          </div>
        </div>
      </div>
      <hr>
      <!-- About -->  
      <div class="row">
        <div class="col-md-12">
          <h4>About <%= @gym.listing_name %></h4>
          <p><%= @gym.summary %></p>
        </div>
      </div>
      <hr>
      <!-- Amenities -->  
      <div class="row">
        <div class="col-md-3">
          <h4>Amenities</h4>
        </div>

        <br>
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-12">
              <ul class="amenities no-bullet">
                <li><% if @gym.is_weights %>Free Weights<% end %></li>
                <li><% if @gym.is_shower %>Showers<% end %></li>
                <li><% if @gym.is_towel %>Towel Service<% end %></li>
                <li><% if @gym.is_yoga %>Yoga Equipment<% end %></li>
                <li><% if @gym.is_cycling %>Cycling Bikes<% end %></li>
                <li><% if @gym.is_boxing %>Boxing Equipment<% end %></li>
                <li><% if @gym.is_pilates %>Pilates Equipment<% end %></li>
                <li><% if @gym.is_pool %>Swimming Pool<% end %></li>
                <li><% if @gym.is_basketball %>Basketball Court<% end %></li>
                <li><% if @gym.is_internet %>Internet<% end %></li>
                <li><% if @gym.is_lounge %>Lounge<% end %></li>
                <li><% if @gym.is_childcare %>Childcare<% end %></li>
              </ul>   
            </div>
          </div>
        </div>
      </div>
      <hr>
      <!-- GOOGLE MAP -->
      <div class="row">
        <div class="container">
          <div id="map" style="width: 100%; height: 400px"></div>

            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBTgBhzcEeEaFvqzoU2dFH8khFTXV5zJEo&callback=initMap"></script>
            <script>
                function initialize() {
                  var location = {lat: <%= @gym.latitude %>, lng: <%= @gym.longitude %>};
                  var map = new google.maps.Map(document.getElementById('map'), {
                    center: location,
                    zoom: 14
                  });

                  var marker = new google.maps.Marker({
                    position: location,
                    map: map
                  });

                  infoWindow.open(map, marker);
                }

                google.maps.event.addDomListener(window, 'load', initialize);
            </script>
        </div>
      </div>
      <hr/>
      <!-- Nearby Gyms -->
      <div class="row">
       <div class="container">
        <h4>Nearby</h4>
        <br>
        <% for gym in @gym.nearbys(5).max(6).shuffle %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= link_to image_tag(gym.cover_photo(:medium)), gym %>
            </div>
            <div class="panel-body">
              <%= link_to gym.listing_name, gym %> <br>
              (<%= gym.distance.round(2) %> miles away)
            </div>
        </div>
        </div>
        <% end %>  
       </div>

      </div>
      <hr>
      <!-- Reviews -->
      <div class="row">
        <div class="col-md-12">
          <h3>
            <%= pluralize(@guest_reviews.count, "Review") %>&nbsp;
            <span id="average_rating"></span>
          </h3>
          <br>
          <div>
            <div><%= render "reviews/guest_list" %></div>
          </div>
        </div>
      </div>
    </div> 
    <!-- Right Panel -->
    <div class="col-md-4">
      <br>
      <!-- Reservation Form -->  
      <%= render 'reservations/form' %>
    </div>
  </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @gym.average_rating %>
  });
</script>

app/views/gyms/update.html.erb
<h1>Gyms#update</h1>
<p>Find me in app/views/gyms/update.html.erb</p>